descriptions:
  start_population_size: "Start population size"
  age_infectiousness_switch: "Age infectiousness switch"
  death_rate: "TB-specific death rate"
  contact_rate: "Contact rate"
  self_recovery_rate: "Self-recovery rate"
  rr_infection_latent: "Relative risk of reinfection while latently infected (ref. infection-naive)"
  rr_infection_recovered: "Relative risk of reinfection after recovery (ref. infection-naive)"
  age_latency:
    early_activation: "Rate of rapid progression to active TB, based on age groups"
    late_activation: "Rate of late reactivation, based on age groups"
    stabilisation: "Rate of stabilization from early to late latency, based on age groups"
  progression_multiplier: "TB progression multiplier"
  seed_time: "Seed time"
  seed_duration: "Seed duration"
  seed_rate: "Seed rate"
  screening_scaleup_shape: "Passive screening shape"
  screening_inflection_time: "Passive screening inflection time"
  time_to_screening_end_asymp: "Time from active TB to be screened"
  base_sensitivity: "Preceding diagnostic algorithm sensitivity"
  genexpert_sensitivity: "GeneXpert sensitivity"
value:
  start_population_size: 1.0
  age_infectiousness_switch: 15.0
  death_rate: 0.1
  contact_rate: 9.54
  self_recovery_rate: 0.29
  rr_infection_latent: 0.12
  rr_infection_recovered: 0.87
  age_latency:
    early_activation: 
      0: 2.4
      5: 2.0
      15: 0.1
      35: 0.1
      50: 0.1
    late_activation: 
      0: 7.0e-09
      5: 2.3e-03
      15: 1.2e-03
      35: 1.2e-03
      50: 1.2e-03
    stabilisation: 
      0: 4.4
      5: 4.4
      15: 2.0
      35: 2.0
      50: 2.0
  progression_multiplier : 1.44
  seed_time: 1881.5
  seed_duration: 19.55
  seed_rate: 70.65
  screening_scaleup_shape: 0.199
  screening_inflection_time: 2009.3
  time_to_screening_end_asymp: 0.336
  base_sensitivity: 0.287
  genexpert_sensitivity: 0.826
unit:
  start_population_size: "person"
  age_infectiousness_switch: "years old"
  death_rate: "per year"
  contact_rate: "contacts per person per day"
  self_recovery_rate: "per year"
  rr_infection_latent:  ""
  rr_infection_recovered: ""
  age_latency:
    early_activation: "per year"
    late_activation: "per year"
    stabilisation: "per year"
  progression_multiplier: 
  seed_time: ""
  seed_duration: "days"
  seed_rate: "persons per day"
  screening_scaleup_shape: " "
  screening_inflection_time: " "
  time_to_screening_end_asymp: " "
  base_sensitivity: ""
  genexpert_sensitivity: ""
sources:
  start_population_size: "A value to avoid dividing by zero in the force of infection calculation"
  age_infectiousness_switch: "Set based on duration of BCG protection [@nguipdop2016, @roy2019]"
  death_rate: "United Nations Population Division data for Indonesia [@unwpp2024]"
  contact_rate: "Fitted [@ragonnet2022]"
  self_recovery_rate: "Fitted [@ragonnet2020]"
  rr_infection_latent:  "Fitted [@andrews2012]"
  rr_infection_recovered: "Fitted [@andrews2012]"
  age_latency: "[@ragonnet2017]"
  progression_multiplier: "Fitted [@ragonnet2022]"
  seed_time: "Fitted [@ragonnet2022]"
  seed_duration: "Fitted [@ragonnet2022]"
  seed_rate: "Fitted [@ragonnet2022]"
  screening_scaleup_shape: "Fitted [@ragonnet2022]"
  screening_inflection_time: "Fitted [@ragonnet2022]"
  time_to_screening_end_asymp: "Fitted [@ragonnet2022]"
  base_sensitivity: "Fitted"
  genexpert_sensitivity: "Fitted"