descriptions:
  start_population_size: "Start population size"
  age_infectiousness_switch: "Age infectiousness switch"
  contact_rate: "Contact rate"
  rr_infection_latent: "Relative risk of reinfection while latently infected (ref. infection-naive)"
  rr_infection_recovered: "Relative risk of reinfection after recovery (ref. infection-naive)"
  age_latency:
    early_activation: "Rate of rapid progression to active TB, based on age groups"
    late_activation: "Rate of late reactivation, based on age groups"
    stabilisation: "Rate of stabilization from early to late latency, based on age groups"
  #progression_multiplier: "TB progression multiplier"
  seed_time: "Seed time"
  seed_duration: "Seed duration"
  seed_rate: "Seed rate"
  screening_scaleup_shape: "Passive screening shape"
  screening_inflection_time: "Passive screening inflection time"
  time_to_screening_end_asymp: "Time from active TB to be screened"
  base_sensitivity: "Preceding diagnostic algorithm sensitivity"
  genexpert_sensitivity: "GeneXpert sensitivity"
  detection_reduction: "Detection reduction"
  post_covid_improvement: "Initial surge in detection post-COVID19"
  #sustained_improvement: "Sustained increase in detection post-COVID19"
  smear_positive_infect_multiplier: "Relative infectiousness of smear-positive TB"
  smear_negative_infect_multiplier: "Relative infectiousness of smear-negative TB"
  extrapulmonary_infect_multiplier: "Relative infectiousness of extrapulmonary TB"
  incidence_props_pulmonary: "Proportion of pulmonary TB cases among all TB cases"
  incidence_props_smear_positive_among_pulmonary: "Proportion of smear-positive TB among all pulmonary TB cases"
  passive_screening_sensitivity_extrapulmonary: "Screening sensitivity for extrapulmonary TB"
  passive_screening_sensitivity_smear_negative: "Screening sensitivity for smear-negative TB"
  passive_screening_sensitivity_smear_positive: "Screening sensitivity for smear-positive TB"
  smear_positive_death_rate: "Death rate for smear-positive TB"
  smear_negative_death_rate: "Death rate for smear-negative and extrapulmonary TB"
  smear_positive_self_recovery: "Self-recovery rate for smear-positive TB"
  smear_negative_self_recovery: "Self-recovery rate for smear-negative and extrapulmonary TB"
value:
  start_population_size: 1.0
  age_infectiousness_switch: 15.0
  contact_rate: 186.386
  rr_infection_latent: 0.242
  rr_infection_recovered: 0.77
  age_latency:
    early_activation: 
      0: 2.4
      5: 2.0
      15: 0.1
      35: 0.1
      50: 0.1
    late_activation: 
      0: 7.0e-09
      5: 2.3e-03
      15: 1.2e-03
      35: 1.2e-03
      50: 1.2e-03
    stabilisation: 
      0: 4.4
      5: 4.4
      15: 2.0
      35: 2.0
      50: 2.0
  #progression_multiplier : 1.429615829051863
  seed_time: 1805.0
  seed_duration: 10.0
  seed_rate: 70.0
  screening_scaleup_shape: 0.167
  screening_inflection_time: 1993.929
  time_to_screening_end_asymp: 1.598
  base_sensitivity: 0.296
  genexpert_sensitivity: 0.912
  detection_reduction: 0.450
  post_covid_improvement: 1.910
  #sustained_improvement: 1.572801967999842
  smear_positive_infect_multiplier: 1.0
  smear_negative_infect_multiplier: 0.25
  extrapulmonary_infect_multiplier: 0.
  incidence_props_pulmonary: 0.96
  incidence_props_smear_positive_among_pulmonary: 0.85
  passive_screening_sensitivity_extrapulmonary: 0.5
  passive_screening_sensitivity_smear_negative: 0.7
  passive_screening_sensitivity_smear_positive: 1.0
  smear_positive_death_rate: 0.418
  smear_negative_death_rate: 0.032
  smear_positive_self_recovery: 0.257
  smear_negative_self_recovery: 0.130
unit:
  start_population_size: "person"
  age_infectiousness_switch: "years old"
  contact_rate: "contacts per person per day"
  rr_infection_latent:  ""
  rr_infection_recovered: ""
  age_latency:
    early_activation: "per year"
    late_activation: "per year"
    stabilisation: "per year"
  #progression_multiplier: 
  seed_time: ""
  seed_duration: "days"
  seed_rate: "persons per day"
  screening_scaleup_shape: " "
  screening_inflection_time: " "
  time_to_screening_end_asymp: " "
  base_sensitivity: ""
  genexpert_sensitivity: ""
  detection_reduction: ""
  post_covid_improvement: ""
  #sustained_improvement: ""
  smear_positive_infect_multiplier: ""
  smear_negative_infect_multiplier: ""
  extrapulmonary_infect_multiplier: ""
  incidence_props_pulmonary: ""
  incidence_props_smear_positive_among_pulmonary: ""
  passive_screening_sensitivity_extrapulmonary: ""
  passive_screening_sensitivity_smear_negative: ""
  passive_screening_sensitivity_smear_positive: ""
  smear_positive_death_rate: ""
  smear_negative_death_rate: ""
  smear_positive_self_recovery: ""
  smear_negative_self_recovery: ""
sources:
  start_population_size: "A value to avoid dividing by zero in the force of infection calculation"
  age_infectiousness_switch: "Set based on duration of BCG protection [@nguipdop2016, @roy2019]"
  contact_rate: "Fitted [@ragonnet2022]"
  rr_infection_latent:  "Fitted [@andrews2012]"
  rr_infection_recovered: "Fitted [@andrews2012]"
  age_latency: "[@ragonnet2017]"
  #progression_multiplier: "Fitted [@ragonnet2022]"
  seed_time: "Fitted [@ragonnet2022]"
  seed_duration: "Fitted [@ragonnet2022]"
  seed_rate: "Fitted [@ragonnet2022]"
  screening_scaleup_shape: "Fitted [@ragonnet2022]"
  screening_inflection_time: "Fitted [@ragonnet2022]"
  time_to_screening_end_asymp: "Fitted [@ragonnet2022]"
  base_sensitivity: "Fitted"
  genexpert_sensitivity: "Fitted"
  detection_reduction: "Fitted"
  post_covid_improvement: "Fitted"
  #sustained_improvement: "Fitted"
  smear_positive_infect_multiplier: ""
  smear_negative_infect_multiplier: ""
  extrapulmonary_infect_multiplier: ""
  incidence_props_pulmonary: ""
  incidence_props_smear_positive_among_pulmonary: ""
  passive_screening_sensitivity_extrapulmonary: ""
  passive_screening_sensitivity_smear_negative: ""
  passive_screening_sensitivity_smear_positive: ""
  smear_positive_death_rate: ""
  smear_negative_death_rate: ""
  smear_positive_self_recovery: ""
  smear_negative_self_recovery: ""
  